//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjDavidFood.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    public partial class tFood
    {
        public int Id { get; set; }

        [DisplayName("品名")]
        public string name { get; set; }
        [DisplayName("價格")]
        public Nullable<int> price { get; set; }
        [DisplayName("種類")]
        public string category { get; set; }
        [DisplayName("產品代號")]
        public string PId { get; set; }
    }
}
