//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjDavidFood.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    public partial class tOrder
    {
        [DisplayName("訂單編號")]
        public int OrderId { get; set; }
        [DisplayName("用戶")]
        public string Uid { get; set; }
        [DisplayName("收件人")]
        public string Receiver { get; set; }
        [DisplayName("收件人電話")]
        public Nullable<int> ReceriverPhone { get; set; }
        [DisplayName("收件人地址")]
        public string RecerverAddress { get; set; }
        [DisplayName("下單時間")]
        public Nullable<System.DateTime> ReceiverDate { get; set; }
        [DisplayName("出貨狀態")]
        public string RecerverState { get; set; }
    }
}
